steps:
  # Create Artifact Registry repository if it doesn't exist
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud artifacts repositories create moveyes-server \
          --repository-format=docker \
          --location=us-central1 \
          --description="Moveyes Server Docker repository" || true

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/moveyes-server/moveyes-server:$COMMIT_SHA', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/moveyes-server/moveyes-server:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'moveyes-server'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/moveyes-server/moveyes-server:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'NODE_ENV=production'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/moveyes-server/moveyes-server:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'